In [6]:
import requests

# Get the data
r = requests.get('https://raw.githubusercontent.com/evgeniiegorov/earthquake/master/data/90-16-jap.csv')

# Save the data
with open("eq_data.csv", 'wb') as f:
    f.write(r.content)

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('eq_data.csv', sep=',')

In [9]:
data[0::10000]

,year,month,date,hour,minute,seconds,lat,long,depth,class
0,1990,1,1,2,19,5.018,42.2734,144.8460,8.0,2.9
10000,1992,12,16,23,2,40.060,35.9000,140.9900,25.0,2.8
20000,1993,11,11,0,6,9.016,39.0242,142.2783,45.1,5.5
30000,1994,12,30,11,26,50.010,39.7400,143.6900,0.0,2.8
40000,1996,3,6,17,32,56.094,35.4420,138.9635,16.0,3.3
50000,1997,10,13,21,7,11.099,41.2873,142.5806,34.0,3.0
60000,1999,4,24,10,40,10.012,36.3780,141.4850,9.5,3.4
70000,2000,6,6,21,27,8.060,36.8930,135.4800,10.0,4.0
80000,2000,7,22,15,18,8.000,34.3500,142.5200,29.0,2.9
90000,2000,12,6,8,25,44.030,32.4900,135.6100,44.0,2.8
100000,2001,12,23,6,58,27.030,34.1200,140.5600,59.0,2.7
110000,2003,7,8,17,14,22.052,34.8577,136.8186,12.1,4.1
120000,2004,9,12,16,17,53.080,33.1300,137.0000,36.0,2.5
130000,2005,10,13,5,28,49.040,35.9300,137.6600,10.0,2.8
140000,2007,4,10,1,22,24.013,38.9598,141.6975,73.7,4.0
150000,2008,9,30,23,30,5.088,33.3130,141.2733,35.0,3.3
160000,2010,5,25,14,53,53.030,31.2700,128.9500,2.0,2.8
170000,2011,3,17,2,38,0.036,36.6771,142.1826,25.2,4.4
180000,2011,4,17,19,49,15.060,36.8600,140.6800,11.0,3.1
190000,2011,6,27,0,19,9.091,34.9465,142.7721,35.0,3.5
200000,2011,10,14,20,54,3.050,39.1400,142.3800,29.0,2.5
210000,2012,3,21,17,47,45.055,40.8428,144.8634,35.0,3.7
220000,2012,10,27,20,29,50.030,39.0300,142.3900,30.0,2.9
230000,2013,9,8,19,26,29.041,38.5745,142.5885,52.6,3.9
240000,2014,12,14,15,1,25.090,35.9200,141.1300,25.0,2.9