In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("significant_eq_database.csv", sep=';', on_bad_lines='skip')

In [5]:
data.head()

,ID Earthquake,Flag Tsunami,Year,Month,Day,Focal Depth,EQ Primary,Mw Magnitude,Ms Magnitude,Mb Magnitude,...,Total Effects : Missing Description,Total Effects : Injuries,Total Effects : Injuries Description,Total Effects : Damages in million Dollars,Total Effects : Damage Description,Total Effects : Houses Destroyed,Total Effects : Houses Destroyed Description,Total Effects : Houses Damaged,Total Effects : Houses Damaged Description,Coordinates
0,78,NaN,334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"41.2,19.3"
1,84,Tsunami,344,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,SEVERE (~>$5 to $24 million),NaN,NaN,NaN,NaN,"40.3,26.5"
2,9989,Tsunami,346,NaN,NaN,NaN,6.8,NaN,6.8,NaN,...,NaN,NaN,NaN,NaN,MODERATE (~$1 to $5 million),NaN,Many (~101 to 1000 houses),NaN,NaN,"41.4,19.4"
3,110,NaN,438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"35.5,25.5"
4,9971,Tsunami,557,NaN,NaN,NaN,7.0,NaN,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"40.9,27.6"

In [6]:
data.isna().sum()

ID Earthquake                                      0
Flag Tsunami                                    4370
Year                                               0
Month                                            408
Day                                              562
Focal Depth                                     2965
EQ Primary                                      1792
Mw Magnitude                                    4874
Ms Magnitude                                    3278
Mb Magnitude                                    4404
Ml Magnitude                                    6024
MFA Magnitude                                   6194
Unknown Magnitude                               5431
Intensity                                       3382
Country                                            0
State                                           5885
Location name                                      1
Region code                                        1
Earthquake : Deaths                             4139
Earthquake : Deaths Description                 3657
Earthquake : Missing                            6187
Earthquake : Missing Description                6187
Earthquake : Injuries                           4964
Earthquake : Injuries Description               4776
Earthquake : Damage (in M$)                     5697
Earthquake : Damage Description                 1762
Earthquakes : Houses destroyed                  5422
Earthquakes : Houses destroyed Description      4504
Earthquakes : Houses damaged                    5718
Earthquakes : Houses damaged Description        5268
Total Effects : Deaths                          4506
Total Effects : Deaths Description              4168
Total Effects : Missing                         6183
Total Effects : Missing Description             6182
Total Effects : Injuries                        4949
Total Effects : Injuries Description            4767
Total Effects : Damages in million Dollars      5752
Total Effects : Damage Description              2915
Total Effects : Houses Destroyed                5391
Total Effects : Houses Destroyed Description    4424
Total Effects : Houses Damaged                  5780
Total Effects : Houses Damaged Description      5387
Coordinates                                       55
dtype: int64

In [8]:
data.isnull().groupby(["Earthquake : Deaths", "Earthquake : Missing", "Earthquake : Injuries", "Earthquake : Damage (in M$)"]).size()

Earthquake : Deaths  Earthquake : Missing  Earthquake : Injuries  Earthquake : Damage (in M$)
False                False                 False                  False                            13
                                                                  True                              8
                     True                  False                  False                           263
                                                                  True                            582
                                           True                   False                           127
                                                                  True                           1076
True                 True                  False                  False                            57
                                                                  True                            321
                                           True                   False                            51
                                                                  True                           3710
dtype: int64

In [10]:
# Let's look at data where Earthquake : Damage (in M$) is missing

missing = data[data["Earthquake : Damage (in M$)"].isnull()].index.tolist()

In [15]:
missing[-4:]

[6202, 6203, 6205, 6206]

In [21]:
data.iloc[6202]

ID Earthquake                                                          10191
Flag Tsunami                                                             NaN
Year                                                                    2016
Month                                                                    8.0
Day                                                                     15.0
Focal Depth                                                              8.0
EQ Primary                                                               5.5
Mw Magnitude                                                             5.5
Ms Magnitude                                                             NaN
Mb Magnitude                                                             NaN
Ml Magnitude                                                             NaN
MFA Magnitude                                                            NaN
Unknown Magnitude                                                        NaN
Intensity                                                                6.0
Country                                                                 PERU
State                                                                    NaN
Location name                                                PERU:  AREQUIPA
Region code                                                            160.0
Earthquake : Deaths                                                      9.0
Earthquake : Deaths Description                        Few (~1 to 50 deaths)
Earthquake : Missing                                                     NaN
Earthquake : Missing Description                                         NaN
Earthquake : Injuries                                                   68.0
Earthquake : Injuries Description                   Some (~51 to 100 deaths)
Earthquake : Damage (in M$)                                              NaN
Earthquake : Damage Description                 MODERATE (~$1 to $5 million)
Earthquakes : Houses destroyed                                         605.0
Earthquakes : Houses destroyed Description        Many (~101 to 1000 houses)
Earthquakes : Houses damaged                                           671.0
Earthquakes : Houses damaged Description          Many (~101 to 1000 houses)
Total Effects : Deaths                                                   9.0
Total Effects : Deaths Description                     Few (~1 to 50 deaths)
Total Effects : Missing                                                  NaN
Total Effects : Missing Description                                      NaN
Total Effects : Injuries                                                68.0
Total Effects : Injuries Description                Some (~51 to 100 deaths)
Total Effects : Damages in million Dollars                               NaN
Total Effects : Damage Description              MODERATE (~$1 to $5 million)
Total Effects : Houses Destroyed                                       605.0
Total Effects : Houses Destroyed Description      Many (~101 to 1000 houses)
Total Effects : Houses Damaged                                         671.0
Total Effects : Houses Damaged Description        Many (~101 to 1000 houses)
Coordinates                                                    -15.64,-71.68
Name: 6202, dtype: object

In [22]:
data.iloc[6206]

ID Earthquake                                                                               10430
Flag Tsunami                                                                                  NaN
Year                                                                                         2019
Month                                                                                         7.0
Day                                                                                          24.0
Focal Depth                                                                                  10.0
EQ Primary                                                                                    3.8
Mw Magnitude                                                                                  NaN
Ms Magnitude                                                                                  NaN
Mb Magnitude                                                                                  NaN
Ml Magnitude                                                                                  NaN
MFA Magnitude                                                                                 NaN
Unknown Magnitude                                                                             3.8
Intensity                                                                                     NaN
Country                                                                                     INDIA
State                                                                                         NaN
Location name                                                       INDIA:  MAHARASHTRA:  PALGHAR
Region code                                                                                  60.0
Earthquake : Deaths                                                                           1.0
Earthquake : Deaths Description                                             Few (~1 to 50 deaths)
Earthquake : Missing                                                                          NaN
Earthquake : Missing Description                                                              NaN
Earthquake : Injuries                                                                         NaN
Earthquake : Injuries Description                                           Few (~1 to 50 deaths)
Earthquake : Damage (in M$)                                                                   NaN
Earthquake : Damage Description                 LIMITED (roughly corresponding to less than $1...
Earthquakes : Houses destroyed                                                                NaN
Earthquakes : Houses destroyed Description                                                    NaN
Earthquakes : Houses damaged                                                                  NaN
Earthquakes : Houses damaged Description                                    Few (~1 to 50 houses)
Total Effects : Deaths                                                                        1.0
Total Effects : Deaths Description                                          Few (~1 to 50 deaths)
Total Effects : Missing                                                                       NaN
Total Effects : Missing Description                                                           NaN
Total Effects : Injuries                                                                      NaN
Total Effects : Injuries Description                                        Few (~1 to 50 deaths)
Total Effects : Damages in million Dollars                                                    NaN
Total Effects : Damage Description              LIMITED (roughly corresponding to less than $1...
Total Effects : Houses Destroyed                                                              NaN
Total Effects : Houses Destroyed Description                                                  NaN
Total Effects : Houses Damaged                                                                NaN
Total Effects : Houses Damaged Description                                  Few (~1 to 50 houses)
Coordinates                                                                             20.0,72.9
Name: 6206, dtype: object